name: Publish to WAS

on:
  workflow_dispatch:
    inputs:
      files:
        description: 'Files to upload'
        required: true
        default: '_site/*'

permissions:
  contents: read

jobs:
  publish:
    name: Publish to WAS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - run: npm run --if-present build:11ty

      - name: Publish ${{ inputs.files }} to WAS
        id: test-action
        uses:  gobengo/wallet-attached-storage-action@main
        with:
          files: "${{ inputs.files }}"

      - name: Print Resource URL
        id: output-resource
        run: echo "${{ steps.test-action.outputs.resource }}"
